const en = {
    welcomeTitle: "Welcome to flipo!",
    welcomeContent01: "This is a quick guide on how to use the app.",
    welcomeContent02: "If you decide to skip this guide, you can repeat it at any time from the settings section.",
    skip: "Skip",
    continue: "Continue",
    sectionsTitle: "App sections",
    sectionsContent01: "flipo has three main sections: Decks, Profile and Settings.",
    sectionsContent02: "You can switch between these in the bottom navbar when you're at the root of the current section.",
    decksSectionTitle: "Deck section",
    decksSectionContent01: "The Decks section is the main section where the most of the app usage takes place.",
    decksSectionContent02: "Here you create and edit your decks, flashcards, and play them.",
    profileSectionTitle: "Profile section",
    profileSectionContent01: "The Profile section is where you can sign in to your Google account.",
    profileSectionContent02: "Once signed in, you can export your local data to your Google Drive and vice-versa.",
    settingsSectionTitle: "Settings section",
    settingsSectionContent01: "In the Settings section you can view the current app settings, like the color theme.",
    settingsSectionContent02: "You can also replay this walkthrough at any time from this section.",
    deckCreationTitle: "Deck creation",
    deckCreationContent01: "To create a deck tap the new deck card and add new flashcards.",
    deckCreationContent02: "Each deck needs at least two flashcards to be created.",
    deckPlaythroughTitle: "Playing a deck",
    deckPlaythroughContent01: "To play a deck, choose it from the menu and then press Play deck. You will be dealt a flashcard.",
    deckPlaythroughContent02: "After flipping a flashcard, rate how well you remembered the card you were dealt.",
    deckPlaythroughContent03: "This rating will affect how often this card will be dealt in the future."
};

const sk = {
    welcomeTitle: "Vitajte vo flipo!",
    welcomeContent01: "Toto je stručný návod na používanie aplikácie.",
    welcomeContent02: "Ak sa rozhodnete tento návod preskočiť, môžete si ho kedykoľvek zopakovať v sekcii nastavení.",
    skip: "Preskočiť",
    continue: "Pokračovať",
    sectionsTitle: "App sections",
    sectionsContent01: "flipo má tri hlavné sekcie: Balíčky, Profil a Nastavenia.",
    sectionsContent02: "Môžete medzi nimi prepínať v spodnom navigačnom paneli, keď ste v koreni aktuálnej sekcie.",
    decksSectionTitle: "Sekcia Balíčky",
    decksSectionContent01: "Sekcia Decks je hlavnou sekciou, v ktorej sa odohráva väčšina používania aplikácie.",
    decksSectionContent02: "Tu vytvárate a upravujete svoje balíčky, karty a prehrávate ich.",
    profileSectionTitle: "Sekcia Profil",
    profileSectionContent01: "V sekcii Profil sa môžete prihlásiť do svojho účtu Google.",
    profileSectionContent02: "Po prihlásení môžete exportovať svoje lokálne údaje na Disk Google a naopak.",
    settingsSectionTitle: "Sekcia Nastavenia",
    settingsSectionContent01: "V sekcii Settings môžete zobraziť aktuálne nastavenia aplikácie, napríklad farebnú tému.",
    settingsSectionContent02: "V tejto sekcii si tiež môžete kedykoľvek prehrať tento návod.",
    deckCreationTitle: "Tvorba balíčka",
    deckCreationContent01: "Ak chcete vytvoriť balíček, klepnite na kartu nového balíčka a pridajte nové karty.",
    deckCreationContent02: "Na vytvorenie balíčka sú potrebné aspoň dve flashkarty.",
    deckPlaythroughTitle: "Prehrávanie balíčka",
    deckPlaythroughContent01: "Ak chcete prehrať balíček, vyberte ho z ponuky a potom stlačte tlačidlo Spustiť. Bude vám podaná flashkarta.",
    deckPlaythroughContent02: "Po otočení flashkarty ohodnoťte, ako dobre ste si zapamätali kartu, ktorú ste dostali.",
    deckPlaythroughContent03: "Toto hodnotenie ovplyvní, ako často bude táto karta v budúcnosti podávaná."
};

const de = {
    welcomeTitle: "Willkommen bei flipo!",
    welcomeContent01: "Dies ist eine Kurzanleitung für die Benutzung der App.",
    welcomeContent02: "Wenn Sie sich entscheiden, diese Anleitung zu überspringen, können Sie sie jederzeit im Bereich Einstellungen wiederholen.",
    skip: "Überspringen",
    continue: "Fortfahren",
    sectionsTitle: "App-Abschnitt",
    sectionsContent01: "flipo hat drei Hauptbereiche: Decks, Profil und Einstellungen.",
    sectionsContent02: "Sie können in der unteren Navigationsleiste zwischen diesen Bereichen wechseln, wenn Sie sich am Anfang des aktuellen Bereichs befinden.",
    decksSectionTitle: "Deck-Abschnitt",
    decksSectionContent01: "Der Bereich Decks ist der Hauptbereich, in dem der Großteil der App-Nutzung stattfindet.",
    decksSectionContent02: "Hier erstellst und bearbeitest du deine Decks, Flashcards und spielst sie ab.",
    profileSectionTitle: "Profil-Abschnitt",
    profileSectionContent01: "Im Profilbereich können Sie sich bei Ihrem Google-Konto anmelden.",
    profileSectionContent02: "Nach der Anmeldung können Sie Ihre lokalen Daten in Ihr Google Drive exportieren und umgekehrt.",
    settingsSectionTitle: "Abschnitt Einstellungen",
    settingsSectionContent01: "Im Abschnitt Einstellungen können Sie die aktuellen App-Einstellungen, wie z. B. das Farbthema, anzeigen.",
    settingsSectionContent02: "In diesem Abschnitt können Sie auch jederzeit diese exemplarische Vorgehensweise wiederholen.",
    deckCreationTitle: "Deck-Erstellung",
    deckCreationContent01: "Um ein Deck zu erstellen, tippen Sie auf die neue Deckkarte und fügen Sie neue Karteikarten hinzu.",
    deckCreationContent02: "Jedes Deck benötigt mindestens zwei Karteikarten, um erstellt zu werden.",
    deckPlaythroughTitle: "Deck-spiel",
    deckPlaythroughContent01: "Um einen Kartensatz zu spielen, wählen Sie ihn aus dem Menü aus und drücken Sie dann Play deck. Es wird Ihnen eine Karte ausgeteilt.",
    deckPlaythroughContent02: "Nachdem Sie eine Karte umgedreht haben, bewerten Sie, wie gut Sie sich die Karte gemerkt haben, die Sie erhalten haben.",
    deckPlaythroughContent03: "Diese Bewertung hat Einfluss darauf, wie oft diese Karte in Zukunft ausgeteilt wird."
};

export { en, sk, de };